anthem = {
        "Albania":"https://upload.wikimedia.org/wikipedia/commons/5/52/Hymni_i_Flamurit_instrumental.ogg",
        "Andorra":"",
        "Armenia":"",
        "Austria":"",
        "Azerbaijan":"",
        "Belarus":"",
        "Belgium":"",
        "Bosnia and Herzegovina":"",
        "Bulgaria":"",
        "Croatia":"",
        "Cyprus":"",
        "Czechia":"",
        "Denmark":"",
        "Estonia":"",
        "Finland":"",
        "France":"",
        "Georgia ":"",
        "Germany":"",
        "Greece":"",
        "Hungary":"",
        "Iceland":"",
        "Republic of Ireland":"",
        "Italy":"",
        "Kazakhstan":"",
        "Kosovo":"",
        "Latvia":"",
        "Liechtenstein":"",
        "Lithuania":"",
        "Luxembourg":"",
        "Malta":"",
        "Moldova":"",
        "Monaco":"",
        "Montenegro":"",
        "Netherlands":"",
        "North Macedonia":"",
        "Norway":"",
        "Poland":"",
        "Portugal":"",
        "Romania":"",
        "Russia":"",
        "San Marino":"",
        "Serbia":"",
        "Slovakia":"",
        "Slovenia":"",
        "Spain":"",
        "Sweden":"",
        "Switzerland":"",
        "Turkey":"",
        "Ukraine":"",
        "United_Kingdom":"",
        "Vatican City":"",
}