anthem = {
        "Albania":"https://upload.wikimedia.org/wikipedia/commons/5/52/Hymni_i_Flamurit_instrumental.ogg",
        "Andorra":"https://upload.wikimedia.org/wikipedia/commons/5/5b/El_Gran_Carlemany.ogg",
        "Armenia":"https://upload.wikimedia.org/wikipedia/commons/c/c7/Mer_Hayrenik_instrumental.ogg",
        "Austria":"https://upload.wikimedia.org/wikipedia/commons/7/7c/Land_der_Berge_Land_am_Strome_instrumental.ogg",
        "Azerbaijan":"https://upload.wikimedia.org/wikipedia/commons/5/5d/Az%C9%99rbaycan_mar%C5%9F%C4%B1_instrumental.ogg",
        "Belarus":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Belarusian_national_anthem%2C_performed_by_the_United_States_Navy_Band.mp3",
        "Belgium":"https://upload.wikimedia.org/wikipedia/commons/e/e8/La_Braban%C3%A7onne.oga",
        "Bosnia and Herzegovina":"https://upload.wikimedia.org/wikipedia/en/d/dd/Bosnia_and_Herzegovina%27s_national_anthem.ogg",
        "Bulgaria":"https://upload.wikimedia.org/wikipedia/commons/4/4f/Mila_Rodino_instrumental.ogg",
        "Croatia":"https://upload.wikimedia.org/wikipedia/commons/d/df/Lijepa_nasa_domovino_instrumental.ogg",
        "Cyprus":"https://upload.wikimedia.org/wikipedia/commons/d/db/Hymn_to_liberty_instrumental.oga",
        "Czechia":"https://upload.wikimedia.org/wikipedia/commons/6/6e/Czech_anthem.ogg",
        "Denmark":"https://upload.wikimedia.org/wikipedia/commons/0/06/United_States_Navy_Band_-_Der_er_et_yndigt_land.ogg",
        "Estonia":"https://upload.wikimedia.org/wikipedia/commons/5/52/US_Navy_band_-_National_anthem_of_Estonia.ogg",
        "Finland":"https://upload.wikimedia.org/wikipedia/commons/6/61/United_States_Navy_Band_-_Maamme.ogg",
        "France":"https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg",
        "Georgia ":"https://upload.wikimedia.org/wikipedia/commons/b/b6/Georgian_national_anthem.oga",
        "Germany":"https://upload.wikimedia.org/wikipedia/commons/a/a6/German_national_anthem_performed_by_the_US_Navy_Band.ogg",
        "Greece":"https://upload.wikimedia.org/wikipedia/commons/d/db/Hymn_to_liberty_instrumental.oga",
        "Hungary":"https://upload.wikimedia.org/wikipedia/commons/7/79/Hungarian_national_anthem%2C_performed_by_the_United_States_Navy_Band_%281997_arrangement%29.mp3",
        "Iceland":"https://upload.wikimedia.org/wikipedia/commons/4/4b/Lofs%C3%B6ngur.ogg",
        "Republic of Ireland":"https://upload.wikimedia.org/wikipedia/commons/7/7c/United_States_Navy_Band_-_Amhr%C3%A1n_na_bhFiann.ogg",
        "Italy":"https://upload.wikimedia.org/wikipedia/commons/c/c0/National_anthem_of_Italy_-_U.S._Navy_Band_%28long_version%29.ogg",
        "Kazakhstan":"https://upload.wikimedia.org/wikipedia/commons/d/d9/Kazakhstan_%28instrumental%29.oga",
        "Kosovo":"https://upload.wikimedia.org/wikipedia/commons/0/0a/National_Anthem_of_the_Republic_of_Kosovo.ogg",
        "Latvia":"https://upload.wikimedia.org/wikipedia/commons/5/55/Latvian_National_Anthem.ogg",
        "Liechtenstein":"https://upload.wikimedia.org/wikipedia/commons/6/61/Oben_am_jungen_Rhein%2C_by_the_U.S._Navy_Band.ogg",
        "Lithuania":"https://upload.wikimedia.org/wikipedia/commons/c/ca/Tauti%C5%A1ka_giesme_instumental.ogg",
        "Luxembourg":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Ons_Heemecht.ogg",
        "Malta":"https://upload.wikimedia.org/wikipedia/commons/8/80/Malta_anthem_%28instrumental%29.ogg",
        "Moldova":"https://upload.wikimedia.org/wikipedia/commons/a/ad/Imnul_Republicii_Moldova_US_NAVY.ogg",
        "Monaco":"https://upload.wikimedia.org/wikipedia/commons/c/c2/Monaco_National_Anthem.ogg",
        "Montenegro":"https://upload.wikimedia.org/wikipedia/commons/a/a2/National_Anthem_of_Montenegro.ogg",
        "Netherlands":"https://upload.wikimedia.org/wikipedia/commons/2/2e/United_States_Navy_Band_-_Het_Wilhelmus.ogg",
        "North Macedonia":"https://upload.wikimedia.org/wikipedia/en/b/b6/North_Macedonia%27s_national_anthem_%28instrumental%29.ogg",
        "Norway":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Norway_%28National_Anthem%29.ogg",
        "Poland":"https://upload.wikimedia.org/wikipedia/commons/b/b1/Mazurek_Dabrowskiego.ogg",
        "Portugal":"https://upload.wikimedia.org/wikipedia/commons/5/58/A_Portuguesa.ogg",
        "Romania":"https://upload.wikimedia.org/wikipedia/commons/7/77/Desteapta-te%2C_romane%21.ogg",
        "Russia":"https://upload.wikimedia.org/wikipedia/commons/4/41/National_Anthem_of_Russia_%282000%29%2C_instrumental%2C_one_verse.ogg",
        "San Marino":"https://upload.wikimedia.org/wikipedia/commons/d/d9/Inno_Nazionale_della_Repubblica.ogg",
        "Serbia":"https://upload.wikimedia.org/wikipedia/commons/8/8e/Serbian_national_anthem%2C_instrumental.oga",
        "Slovakia":"https://upload.wikimedia.org/wikipedia/commons/e/e8/Nad_Tatrou_sa_bl%C3%BDska.ogg",
        "Slovenia":"https://upload.wikimedia.org/wikipedia/commons/3/30/Slovenia%27s_national_anthem%2C_performed_by_the_United_States_Navy_Band.oga",
        "Spain":"https://upload.wikimedia.org/wikipedia/commons/c/c8/Marcha_Real-Royal_March_by_US_Navy_Band.ogg",
        "Sweden":"https://upload.wikimedia.org/wikipedia/commons/0/02/United_States_Navy_Band_-_Sweden.ogg",
        "Switzerland":"https://upload.wikimedia.org/wikipedia/commons/0/00/Swiss_Psalm.ogg",
        "Turkey":"https://upload.wikimedia.org/wikipedia/commons/5/50/IstiklalMarsi-2013.ogg",
        "Ukraine":"https://upload.wikimedia.org/wikipedia/commons/6/6d/National_anthem_of_Ukraine%2C_instrumental.oga",
        "United_Kingdom":"https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg",
        "Vatican City":"https://upload.wikimedia.org/wikipedia/commons/d/d1/United_States_Navy_Band_-_Inno_e_Marcia_Pontificale.ogg",
}